### ISSUE TITLE
"Can't find any Google account on this devie" Error trying to sign in

### ISSUE THREAD

**Issue by esQmo** [mabahmani/radioamin-android#3]
Build the app from source. On app launch, when clicking on  Sign in, there is a toast message displaying about the Google account missing.

**Comment by mabahmani** [comment]
Thanks for build app and testing.
At this moment the app is in test mode and not released so just google accounts that are intrudused as test developers can sign in.

You can only test offline mode.

Because it was an training app for my learning java-backend project the backend is not completly ready. And is in localhost.

**Comment by esQmo** [comment]
I'm actually linking it to my remote web backend through REST API
